baseURL = "https://www.francomontenegro.com.ar"
languageCode = "en-us"
title = "Franco Montenegro"
theme = "hugo-tailwind-journal"
copyright = "Franco Montenegro"
pygmentsCodeFences = true
pygmentsUseClasses = true
useHLJS = true

[taxonomies]
    tag = "tags"

[params]
    author = "Franco Montenegro"
    avatar = "avatar.jpg"
    description = "I like programming and casually, I write about it."
    tagline = "I like programming and casually, I write about it."
